name: easy_firebase_notification
description: "Easy Firebase Notification"
version: 0.0.1
homepage: https://github.com/yavuzfeti/easy_firebase_notification

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: